---
galaxy_info:
  author: HuyVT
    description: DNS server (Technitium DNS)
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
